### ISSUE TITLE
GeneSet issue with singscore

### ISSUE THREAD

**Issue by NMaziak** [DavisLaboratory/singscore#18]
Hello, 

I was wondering if you could provide how the tgfb genesets were derived. These sets work, but when I have made ones I'm having a hard time making my gene list (which is just the gene symbols e.g. KRT19, AGR2...) to be properly set up with the same geneIds method as you have used. I'm sorry, I'm very new to this and have been stuck on how to move forward. 

Cheers,
Noura

**Comment by bhuvad** [comment]
Hi Noura,

Thanks for using singscore. Singscore accepts simple character vectors (e.g. `sig<- c('KRT19', 'AGR2')`) so you do not necessarily need to create a GeneSet object (which is what we usually create). If you are keen to create a GeneSet object, you can do so as shown below:

```
library(GSEABase)

sig_genes <- c('KRT19', 'AGR2') #you can use this directly in simpleScore
sig <- GeneSet(sig_genes, setName = 'MySet')
```
