### ISSUE TITLE
MSigDB gene sets can be used for singscore?

### ISSUE THREAD

**Issue by JasmineUT** [DavisLaboratory/singscore#19]
Hello,

I was just wondering if MSigDB gene sets can be used for singscore analysis. We would like to use "H: hallmark gene sets". Would that be possible for you to provide how gene set can be generated from MSigDB using GeneSet function?

Thanks a lot,
Jasmine

**Comment by bhuvad** [comment]
Hi Jasmine,

There are quite a few approaches to loading MSigDB gene sets into R. One way is to create these gene sets using the GSEABase package. The `GSEABase::getBroadSets()` function in the package will automatically read broad sets from the provided URL or an XML file downloaded from MSigDB (for instance the Hallmarks XML file). This is the easiest approach to load these genesets. The function generates a GeneSetCollection object which can be passed onto the `singscore::multiScore()` function to score your ranked data against. If you want to score using individual signatures, you can always subset the GeneSetCollection as you would a list, for example, myGeneSetCollection[[2]] for the second set. This can then be passed onto the `singscore::simpleScore()` to score your data against a single signature.

Cheers,
Dharmesh
