### ISSUE TITLE
Overview Plot Request

### ISSUE THREAD

**Issue by DarioS** [DavisLaboratory/singscore#23]
It would be nice if an overview heatmap function was available that put each pathway into a row and each sample into a column and the colour of the box was the enrichment score. This would visually identify pathways enriched in groups of samples and also those specific to one or two samples, which are also interesting.

**Comment by bhuvad** [comment]
Hi @DarioS,

This is a bit tricky to do within the package as there are way too many decision points. We had thought of this earlier on too, however, we concluded that this was best left as a user-end task. One of the decisions that can impact interpretation is whether to use raw scores, or z-score normalised scores (which is often done for heatmaps). Such normalisation would be dependent on the number of samples and my only work if there are enough and diverse samples. Additionally, the user may wish to annotate samples using numerous factors. We may still consider implementing this as a function if a few users request it and provide input on what they would like to use such plots for (as we can then customise functions accordingly). For the time being, I highly recommend using the `ComplexHeatmap` (https://bioconductor.org/packages/release/bioc/html/ComplexHeatmap.html) package to plot your heatmaps. If you have a score matrix (for instance from `multiScore()`), you can use it directly using functions from the `ComplexHeatmap` package to produce heatmaps. This package is extensively documented and very powerful (https://jokergoo.github.io/ComplexHeatmap-reference/book/).

Thank you for the suggestion and your feedback! I always keen to figure out new ways to visualise results from singscore!

Cheers,
Dharmesh
