### ISSUE TITLE
Error running generateNull function 

### ISSUE THREAD

**Issue by Dagsbio** [DavisLaboratory/singscore#34]
I get this error when running

permuteResult <- generateNull(rankData = ranked_cell_lines,upSet=patri_gene_sets)

![image](https://user-images.githubusercontent.com/23311037/151217564-280d1bdd-1aec-46b5-8924-902f16328ad2.png)

Any ideas how to solve this?

**Comment by bhuvad** [comment]
Hi,

I apologise for the delayed response. The error is telling you that none of the genes in the gene-set match up with those from the expression data (rank matrix in your code). Please check the rownames of the `ranked_cell_lines` object and check whether the genes in `patri_gene_sets`) match up. 

Cheers,
Dharmesh

**Comment by Isaacyz** [comment]
HI I get the error, like this:
![Screen Shot 2022-06-11 at 6 26 55 pm](https://user-images.githubusercontent.com/95325026/173180054-a05307b6-ccde-4f5f-b283-6c54544bd16b.png)
**ranks** is file from **rankGenes()** with gene names in rows and sample as columns.
"**gl**" is  a geneset vector  
![Screen Shot 2022-06-11 at 6 31 09 pm](https://user-images.githubusercontent.com/95325026/173180224-30f7a319-6dd6-4492-9f3e-044648e0f29e.png)
and they r all in the row name of ranks file:
![Screen Shot 2022-06-11 at 6 32 14 pm](https://user-images.githubusercontent.com/95325026/173180277-ac638d90-9f6e-4ef5-b8bb-5a5ca2585c3c.png)
How can I fix this error? Thx

**Comment by Isaacyz** [comment]
I just tried to convert **ranks** file from data.frame to **"matrix" "array"** which is the same table format in Ruqian Lyu's Singscore tutorial, but with such error:
![Screen Shot 2022-06-11 at 6 50 59 pm](https://user-images.githubusercontent.com/95325026/173180987-b250ae34-b528-4cad-b789-89e7a1057ea5.png)
It's ok to run the **generateNull()** in Ruqian's tutorial not my own ranks file.

**Comment by ruqianl** [comment]
Hi @Isaacyz ,

Thanks for using our tool.
Could you share the `ranks` data object (saved as `.rd`) file so I could run a bit of troubleshooting on my side?

Ruqian

**Comment by Isaacyz** [comment]
Hi Ruqian,
Thanks that will be helpful!
I here is the file ("*rank_example.rda*") which raise the same errors I
list before if I run follow commands:
"""
library(singscore)
library(GSEABase)
gl <- c("GZMA","PRF1")
gl <- GeneSet(gl)
permuteResult <-
  generateNull(
    upSet = gl,
    rankData = temp_rank,
    subSamples = 1:2,
    B = 1000,
    ncores = 1,
    seed = 1)
permuteResult <-
  generateNull(
    upSet = gl,
    rankData = as.matrix(temp_rank),
    subSamples = 1:2,
    B = 1000,
    ncores = 1,
    seed = 1)
"""

**Comment by ruqianl** [comment]
Hi @Isaacyz ,

Thanks for sending over the data via email.
I have had a brief look into the error you had. I see that your rank file was not by the function `rankGenes()` and  it caused some input signature solving issues in the called functions.

To work around this here is what you could do:
```
temp_rank_m <- as.matrix(temp_rank)
attr(temp_rank_m,"stable") <- FALSE
permuteResult <-
  generateNull(
    upSet = gl,
    rankData = temp_rank_m,
    subSamples = 1:2,
    B = 1000,
    ncores = 1,
    seed = 1)
```

**Comment by bhuvad** [comment]
Hi @Isaacyz,

The solution that Ruqian has presented above will work but I would strongly advise against modifying the ranking matrix that is created by `rankGenes()` unless absolutely required. The boundary computation within singscore relies on ranks being computed as specified by rankGenes therefore post-hoc modification may result in scores that are outside the normal bounds of scores. If you had ideas on how you would alter ranks and what purpose such an alteration would serve, please let us know as it could help us improve the package.

Cheers,
Dharmesh
