### ISSUE TITLE
Unable to create a gene set

### ISSUE THREAD

**Issue by Bioinformatika-BWID** [DavisLaboratory/singscore#35]
Hi, 
Can you kindly show me the code you used to create tgfb_gs_up?
I am trying to create a geneset object for analysis in singscore and it is proving impossible because it is not clear what line of code you used. 

I used this line of code and got the following error.

Kind regards 

![image](https://user-images.githubusercontent.com/84850507/173185837-7d343137-5a8b-49a3-92d3-2f50ba909915.png)

![image](https://user-images.githubusercontent.com/84850507/173185850-9a8536b5-afca-4b7a-80f8-a9ff9d08c3c0.png)

**Comment by ruqianl** [comment]
Hi @bioinformaticulus ,

Thanks for trying our tool. 

A short example of creating a GeneSet object:
```
BiocManager::install("GSEABase")
BiocManager::install("GO.db")
library(GSEABase)
GeneSet(geneIds = c("geneName1","geneName2"), geneIdType=SymbolIdentifier())
```

To view more details of the GeneSet class

`?GSEABase::GeneSet`

And the error you had regarding GO would be resolved by installing the GO.db package `BiocManager::install("GO.db")`

Ruqian

**Comment by Bioinformatika-BWID** [comment]
Thank you very much, I will try that now.
