### ISSUE TITLE
How do you calculate "dispersion"?

### ISSUE THREAD

**Issue by BirongZhang** [DavisLaboratory/singscore#38]
Hi singscore team,

Thanks for sharing this useful tool! Brilliant work!

I would like to know how you calculate dispersion. Is it possible to give me a brief introduction or share with me some tutorials? Or it is just like alpha diversity?

Any advice would be highly appreciated! Thanks.

Kind regards,
Birong

**Comment by bhuvad** [comment]
Hi Birong,

We calculate it by computing the median absolute deviation of ranks. This is detailed in the original publication https://doi.org/10.1186/s12859-018-2435-4.

Cheers,
Dharmesh
