### ISSUE TITLE
Install from Github fails on RStudio

### ISSUE THREAD

**Issue by quarkstar-codes** [DavisLaboratory/singscore#39]
Installing on RStudio using command:
`devtools::install_github('DavisLaboratory/singscore')`

Throws up the error:
```
ERROR
Authors@R field gives more than one person with maintainer role:
Dharmesh D. Bhuva <bhuva.d@wehi.edu.au> [aut, cre] (<https://orcid.org/0000-0002-6398-9157>)
Malvika Kharbanda <kharbanda.m@wehi.edu.au> [aut, cre] (<https://orcid.org/0000-0001-9726-3023>)
```

Reading the `Writing R Extensions` documentation:
```
The mandatory ‘Maintainer’ field should give a _single_ name followed by a _valid_ (RFC 2822) email address in angle brackets.
```

I think the `DESCRIPTION` file syntax does not allow for 2 co-maintainers or it will fail to install using Devtools on RStudio

**Comment by bhuvad** [comment]
Hi! Apologies for the delay in getting back to you. I have fixed this and made Malvika the sole maintainer. This should have fixed the issue.
