### ISSUE TITLE
consistency between the vignette and overview page on GitHub

### ISSUE THREAD

**Issue by MomenehForoutan** [DavisLaboratory/singscore#4]
We should be consistent in the documentation @Rachael-rq, it would be great if you could check them and make sure about this consistency. Thanks! Here are a couple of examples:

- For installation of the package, the link on the overview page is "DavisLaboratory/singscore", while it is "https://github.com/Rachael-rq/'singscore'" in the vignette. It should be "DavisLaboratory/singscore" everywhere.
- In the vignette, we have rankGenes(), however, it is rankExpr() on the overview page and help page of a couple of the functions; I think we decided to go with rankGenes @bhuvad, right? 

Maybe we do not need to include any example in the overview page, only the installation would be fine as we have all the examples in the vignette? What do you guys think?
Thanks!
Sepideh

**Comment by ruqianl** [comment]
Yes, I'll check the docs to make sure they are consistent.
We agreed with rankGenes(), and rankExpr() is the internal function's name.
