### ISSUE TITLE
annot argument issues in plotDispersion 

### ISSUE THREAD

**Issue by annaquaglieri16** [DavisLaboratory/singscore#8]
Hi there, 

it looks like when you try to run the function:

`plotDispersion(scoredf,annot = factor(samples$Outcome),isInteractive = FALSE)`

the input for `annot` should be a vector external from `scoredf`. 

When running something like this:

`plotDispersion(scoredf,annot = factor(scoredf$Outcome),isInteractive = FALSE)`

after merging `scoredf` with sample's annotations, then the points are coloured by the first available column of `scoredf` in alphabetical order. 

Cheers, 

Anna

**Comment by bhuvad** [comment]
Hi Anna,

I have just made an update to the github version of the package that now allows multiple ways to specify your annotations. Annotations can be either discrete (factors and characters) or continous (numerics).

The `annot` argument can be used to pass the vector containing annotations as before. Additionally, annotations can be appended to the `scoredf` as a column and only column name alone can be specified as below:

`scoredf$Outcome = samples$Outcome`
`plotDispersion(scoredf, annot = 'Outcome', isInteractive = FALSE)`

In case you choose to use an independent vector containing the annotations of interest, the plotting functions now allow the `annot_name` argument which allows you to label the legend.

We will be pushing these changes as an official update for the package when possible soon. Feel free to use the version on github in the mean time and help us idendify any more improvements/bugs.

Cheers,
Dharmesh Bhuva
